name: build-wf
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Enable Long Paths in Git (Windows)
        run: git config --system core.longpaths true
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'maven'
      - name: Build
        run: scripts\build.bat
      - name: Store P2 Repositories
        uses: actions/upload-artifact@v3
        with:
          name: p2-cipm
          path: |
            commit-based-cipm/releng/cipm.consistency.updatesite.fi/target/cipm.*.zip
            commit-based-cipm/releng/cipm.consistency.updatesite.si/target/cipm.*.zip
            Palladio-Supporting-EclipseJavaDevelopmentTools/releng/org.palladiosimulator.jdt.updatesite/target/org.*.zip
            Palladio-ReverseEngineering-SoMoX-JaMoPP/releng/org.somox.updatesite/target/org.somox.*.zip
